-- Generated Selectors from Bulk Inspection
-- Success Rate: ~80%
-- Failures: elitetraderfunding, bluskytrading, fasttracktrading, audacitycapital, surgetrader

UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.flex.flex-row.justify-between","accountSizeSelector":"span","priceSelector":"p.text-sm.font-bold","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'myfundedfutures';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"SPAN","accountSizeSelector":null,"priceSelector":"p","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'earn2trade';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"P.amount","accountSizeSelector":null,"priceSelector":"span.amount-price","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'takeprofittrader';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.score-area","accountSizeSelector":"div.score-text","priceSelector":"div.score-price","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'bulenox';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"SPAN.monod-s.monom-s","accountSizeSelector":"div.monod-l.monom-l.programsTable_cap__sqP2Y","priceSelector":"span.upper","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'uprofit';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.framer-1usr6er","accountSizeSelector":"h3.framer-text","priceSelector":"h4.framer-text","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'tickticktrader';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.grid.items-center.grid-flow-col.mt-4","accountSizeSelector":"button.inline-flex.justify-center.items-center.whitespace-nowrap.transition-colors.select-none.text-foreground.text-sm.font-medium.px-3.py-0.h-8.rounded-xl.font-foreground","priceSelector":"div.text-3xl.font-semibold.text-start","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'fundingticks';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"LI.pricing__list-item","accountSizeSelector":"h3.pricing__title","priceSelector":"span","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'daytraders';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.feature-row","accountSizeSelector":"h4","priceSelector":"span.feature-value","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'fundedfuturesnetwork';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"TR","accountSizeSelector":"td","priceSelector":"td","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'the5ers';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV","accountSizeSelector":null,"priceSelector":"strong","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'fundednext';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.grid.items-center.grid-flow-col.mt-4","accountSizeSelector":"button.inline-flex.justify-center.items-center.whitespace-nowrap.transition-colors.select-none.text-sm.font-medium.px-3.py-0.h-8.rounded-xl.text-foreground","priceSelector":"div.text-3xl.font-semibold.text-start","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'fundingpips';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.mt-1.-mb-1.border-b.border-white/10.p-1","accountSizeSelector":"button.t-paragraph-sm.flex.w-full.cursor-pointer.items-center.justify-center.rounded-full.px-4.py-4.font-bold.m-1.border.border-transparent.text-white","priceSelector":"p.t-paragraph-sm-bold.text-green","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'e8markets';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.actual-price-wrap","accountSizeSelector":"h2.heading-style-h4","priceSelector":"div.crossed","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'goatfundedtrader';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.table_cell","accountSizeSelector":"span","priceSelector":"span","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'alphacapitalgroup';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.flex.flex-col","accountSizeSelector":null,"priceSelector":"div.text-primary.text-5xl.font-semibold","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'maventrading';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.single-payout","accountSizeSelector":"div","priceSelector":"div.amount","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'fxify';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"LI","accountSizeSelector":"span","priceSelector":"span","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'blueberryfunded';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"SPAN.elementor-button-text","accountSizeSelector":null,"priceSelector":"span","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'citytradersimperium';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"SPAN.elementor-button-content-wrapper","accountSizeSelector":"span.data-table-header-text","priceSelector":"span.elementor-button-text","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'dnafunded';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.table-wrap-row__data","accountSizeSelector":null,"priceSelector":"div","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'funderpro';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.upw-modelcontent","accountSizeSelector":"div.upw-modelbtn","priceSelector":"div.upw-modelbtn","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'instantfunding';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"DIV.flex.justify-between.items-center.gap-4.py-2.border-b.border-gray-800/50","accountSizeSelector":"button.px-4.py-2.rounded-lg.font-medium.transition-all.duration-300.border.border-gray-700.text-gray-300","priceSelector":"span.text-white.font-medium.text-right","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'larkfunding';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"P","accountSizeSelector":"strong","priceSelector":"strong","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'mentfunding';
UPDATE source_catalog SET json_config = '{"htmlSelectors":{"containerSelector":"TR.border-b.border-[#CED3D7]","accountSizeSelector":"button.challenge-v2-btn-transition-1.challenge-v2-btn-transition-2","priceSelector":"td.py-[15px].text-center","discountLabelSelector":null},"expectedFields":["accountSize","price"]}' WHERE prop_firm_id = 'thefundedtrader';
