openapi: 3.0.0
info:
  title: OnlyPropFirms MVP API
  description: Phase 0 MVP API for validating core business logic.
  version: 0.1.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local Development

paths:
  /prop-firms:
    get:
      summary: List all prop firms
      description: Returns a paginated list of available prop firms.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
        - in: query
          name: size
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: A list of prop firms
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PropFirmSummary'
                  total:
                    type: integer

  /prop-firms/{id}:
    get:
      summary: Get prop firm details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detailed information about a prop firm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropFirmDetail'
        '404':
          description: Firm not found

  /filter-firms:
    post:
      summary: Filter prop firms
      description: Returns firms matching specific criteria (account size, rules, etc.)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilterRequest'
      responses:
        '200':
          description: Filtered list of firms
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/PropFirmSummary'
                  matchCount:
                    type: integer

components:
  schemas:
    PropFirmSummary:
      type: object
      properties:
        id:
          type: string
          example: "apex-trader"
        name:
          type: string
          example: "Apex Trader Funding"
        logoUrl:
          type: string
        rating:
          type: number
          format: float
          example: 4.8
        minFunding:
          type: integer
          example: 25000
        maxFunding:
          type: integer
          example: 300000

    PropFirmDetail:
      allOf:
        - $ref: '#/components/schemas/PropFirmSummary'
        - type: object
          properties:
            description:
              type: string
            websiteUrl:
              type: string
            profitSplit:
              type: string
              example: "90/10"
            evaluationFee:
              type: number
              example: 147.00
            tradingPlatforms:
              type: array
              items:
                type: string
              example: ["NinjaTrader", "Tradovate"]
            affiliateLink:
              type: string

    FilterRequest:
      type: object
      properties:
        accountSize:
          type: integer
          description: Desired account size (e.g., 50000)
        maxPrice:
          type: number
          description: Maximum monthly price willing to pay
        platforms:
          type: array
          items:
            type: string
